{% set name = "marbles-core" %}
{% set pipname = "marbles.core" %}
{% set version = "0.12.1" %}
{% set sha256 = "524be83780913ea0fb8813ab24d47747ecd07375f12ce1b2ec59b3520c675bbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ pipname }}/{{ pipname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5,<3.7
    - pip
  run:
    - python >=3.5,<3.7

test:
  imports:
    - marbles.core

about:
  home: http://github.com/twosigma/marbles
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Read better test failures.
  description: |
    marbles is a Python unittest extension that allows test authors to write
    richer tests that expose more information on test failure to help you
    debug failing tests faster.
  doc_url: https://marbles.readthedocs.io/
  dev_url: https://github.com/twosigma/marbles

extra:
  recipe-maintainers:
    - thejunglejane
    - leifwalsh
