travis:
  secure:
    BINSTAR_TOKEN: VkYuGwwV6kV6boCifZ88GxFntnrgOnJ43EZuPjzZmm8F1mOQ369Te0ElcwNrIcRns64yDlbqB9g+IGuV40D6mHLI3VWi7Hm4kwWyfWtFqLnMJlOS7NDWtIUOxBc34UgEErY5cKrYdJemdESfwKpJDkFdWeq1R3r0pdi4y28l1wwiIJu/iqjdxpo6RyYEQRfe9sUZ7G6Z0t2EDiL3Wo62PJO87qEpLNcr43/P2UacxA1314FNXIBD5sVlIJi/aUxL7lI3/X/f0aTWfgMvqeyDvztJH73MN459rqd+p5tb239ryXriDy79QF8H7OoQSiSLkKvMadZyBWBDS81pBgJPW/0+AU6PybAdOp1kxrqAAYydKPvjpqLaCE81TJ5cWXOr2Fl0cr/e5K1TB7/1EAuJJEabL1cDuOw9GxPDF3DGXeZkkjJkJ5vl7qNJs5woOfYAlhQ7Bzc7xQyMNctD+0VhY+eWzroya81dShDTZBxf9up/7JsO8hQhNWiikiXQZGw3tl+eiaEXzyg3XATPMLw/I+VQmpcFHzgxYY0lVg9yebyx8/+jmoCOpxfLwndyzsphDc2nzu85cyhwuSh/QkL/kGbYT3+kKkA67inBsH9Mvy5sLF+AzLX3c1kaYgvhUHriGr2JJA7ShPcCMzyJBqftnkx0jx1On1nJ78xUCwmwAdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
