travis:
  secure:
    BINSTAR_TOKEN: CoL0CDs7ubveQzx2jA39qerV/BTgqQM5Wf7AhpcBdSJQzYE23uHXwG4pFv51uqXCMubeCJhTeZAdt2Jfxs27olgeArTfIxRq4CPhrnmlYh4pCrcAN3HzSXmhTCnA33ju6EFGAMsFzG6c2hPMGC/7z7J9AhUIajZJ/bYLovOEfdX35oa1z40lZ3M2EMStISjQZ9bEWbPIg2Pf4QwtTnJ7KlEveD4ytDVdfyR4dqmMpoQtKM44IZSp4AYz7CUw891FrS+PVR1tlQ7HJo9bQiWTA2la42oUXOsyb1z9hYmlwrEq6rhnJmmhGlQ/l7n5Kn2bNm8Cu9RBgtstqEzjg2ChKGu8p20GUxWJ1rtBzT52MTGRrRLQ2e20SkCsWPunBVav/QbIwWcBprh69a5fQwxQyGABie7dx52Kd/FBG3wf/14m7EcQFi2dC0pbvOb3D/8MYsE+G5QtBLBEaN+hZ7iAJsASOaKYy7WdzmLUOLxrsbs0pnOy92boXdx++TB05o5ijs2ox2JXbJCq1u65l/dzQ80+fWkIHkLJiCow335Yg2EL86AM7Lsc4MJAU+gsKBBM+1n5/vVjlCmSE94xIJUagv4A27Isl829aZsiiWAEDhcfMjJ+5EYWBcknzBV4IEF3yzTyDUHovsJhB7rULT9MtaM0WVIrdDc8soRzBhegQ18=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
