travis:
  secure:
    BINSTAR_TOKEN: filuVazTeCvKSiaZwn6MjTuTDuGu4ckPE8yOJ79FP8QlBAhCaXYLQazsiBce61keWr6QCHGlJnkQg78P8OnZagmQwfwbnMNR1iAVMQkH6A3MkPLKa8Y2iKcO/SI7UqYkBqF4Kxeiy5bMZdjMkzhfbk7p9ROm/pG0NIxTP57EXIcyrLgyvqHIfyyd71t0JxnaLiKPK48HItubmjkyOo1D6kJk2LXTvuA8rqVCuXHw/6jysnac5l5A5dpAW+3jJEHXsqXEGnnWlQzS36E9VVCNY4UP4fLmJeRGOG/jzD+0UZlMIUz2Y9rIIKv5K0GIJ8L06Mc7ePPw2Wb3iB16Db0vbKUa6WlWeZ+F8mJjxUC1E/fyHDjnyexqiIajBC7VyaEJ049rL9iqYFresSa6yd6gOXfg1s/a/nbKLzAmzQPuD76aRyb9A2GLUmW4v6nS4X+XwBYtXTdzqSewErjkUW/WedIJ1lpUpHzBUtx6SIRLwg/FVo73wsKM5NxJ69QgwxpvFo+kxnBqTIiqBadwVImnl8otINRl1e0F0M16STDtd5/OAFRgkOYsEd2umQN5Mu4ENc2lLbJ7gOpmhuAtye2oov9DQxdkHDHy0B6g95MIizjY19VIpqNocRw+R3eSJUaFWk2BbiKOphkb7qry24/Ra3WtCOlLzzVu5igL5btCrLc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
