travis:
  secure:
    BINSTAR_TOKEN: 0ob0nF4iK+M1DWxbkAwNjxB5QT0vDoedOqYTPJ9cNVwx69SEW0sjeNqWn5Tfj2of0CvE2UynXZA8tNth6sdgxrwBCcb1LlipCf+0QyMXHo15E3gWso/ZHDq4Xgs0nCAZCcRVjI/GQ9SAsCjcck2SPn9PP+gGmUCFENyqjRxdTlkom5TbOzBOh3ziWXBiTb31QpIUaMV8+Nkff0cZ2rfBwkGa/HUAawBra9vL3Ofu7ihr9Pbc1jCcr81cZ2Pe4LWVQawgjOhzuOLn6yF2Ij+o7jyOZB4X917waBME4QLtcO0skJBQBvVxvbnKES5Fbr4xV3KkLQsUjQs2LqL8mLlcVAkHKfkimS0oLe3IU2GgG+oswFxblMpm31VoeiwnbJ4XTAgVa9zFPKb2In597UAzL+j0JffKjQPDsLtt+n1+IWHGjBCvzXfPXdTms8WItb0Cxm5luhd7X12EpH95tZvloj6JGQGYD8PPP3lZVR0kohsiaAvgXIuAMUXfQxgoGTOwoZff+l66ekQmd3k23LiND76sm44C9WwemNIooAwoUws0w53ahDIjJdnUgMJPt46kAfpJ6nHdZqv38l+VWBocWrM9jWhjsOeYn2ExaX7p8ZHIfagynXJizdyRCXkpBpgGh4jwxwlQHvDlwQIZx0N+qbtspoDuGAPGHkJdlNRMOUI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
