travis:
  secure:
    BINSTAR_TOKEN: biTI8Lo/bOHIwdK7MsPOs+HKU5+tB8Ym6/ciqeNhgFPIIAPIj/uqGDUdGySELXOo67nHwVw7EPXLv6CLUSz15EVzJsHONPAC8rvslmh2+IowZLqaboRDo5oMCGZVHpoljEX0jJAe1B/hf0tNvtrkwtKOiJALnvh/LlgU/Q15QJkynMaSNIKV8cITbHUX6qDZRkMPqd5fYGCTzz3NCXU7jzQ8d0Fs88XG1WWnbAw/0vqQYt8pVm8Q+ZVBIT00/g7a32fROx3frR76ye0QHeoPDXL2sZVph6yNtaFCNO4ba3k1BdKMVI8Z48B7KP6HF4Tw2/iN5kMhGhw40z89+Y2uCJ/2jAXw5m5qv/NF7acrL2nfJPNgLJRuBSVlE7AWBKU3a5N6bJa5XkG6ksrOIgU5+FmznBhqcy2FoCISr5iFo4zqF0ogb/MMeEXiC1YRTaXw/FmfVvb7e9283JEWR42xUIDEN7FK91VvyYLpGeiG0/qLQccq1MSVN62gR42mKkPf2vFe3Y12JOpSmzk4hSHkrAe9MQSgvLl9Lm8pMA6ZlCU1c+PmyovKc84IPl9TFjqQjJpI0wcNG1y13/XRDsmfq9+h12Gnfm77dQCmfo7ZwuHITaMAd4KNXldpd9taRnVtpJUMtAB7OjoThFcJ/w+F4nE5BjWZh6Ad5lg7yXO9xlo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
