travis:
  secure:
    BINSTAR_TOKEN: hYgrrF99OUAVu+dzGITFwTuvC9dIUi54l7o9g/jutj5hBs5oKzpgt6XR0uxPvv81FtxAfgabuWRzD8VLEJMv3jPbSJP/GIkBKphBaz6mIrHyvnsOGzXyOV/buHlW381uWeglgr1SfJziBOfFokjPPXItDx0KFuD+8UEjK/QRiOOT5wpnr0Q+HEBUdvzt7oDEu7Wkxe+2H2kMDag0G1p+H+p+w+GRvGBAf+EoctBFLJErT1rC/fq+R9tFbzxhs7j3KvzzXSlMNog2icZPc+mLjbHM/J0LXUTO0tpCFIYkNLSp0+GFz0v/QvdflLPmGD9STioOmnPf7AhhufrNUKBuGbzxdzZRGEqKs3PQNtJmibUk0IbohKHYxRW/G8pJ9R3MFBSwcZrXqvncUw8TU+Puc9EQRRq/+O+mHIW+kom16TJHn3DAsmycBTTDP1OXsdkl5XBeUQ04mUjl+Ox7AlcWivtuBYGauLfXUkEOUKvAoiM02VaX+L8FIbaASsVgFDlaqNT/6HKOBkRt8fayYZAXDNyQg7aXzgzT3dSlXLPZhQoxpzYPGoLJNI51gY1BTkTAQg+Co/uJ+3Xw+Q66pvU4uc3jKAmGYqcmuqSQVR0ZMH9ooSM+leS/cdNmwRXVJ2UOYHfNjAEhm1ssmQ8zUwyMTnrR/7P989IzhsnoaLci4b4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
