travis:
  secure:
    BINSTAR_TOKEN: dEidYIiXydWT1dgu/UGLKiLabZ1J0veOL4YJS2Fa6Subd8T70/XdoBfW677yKG1oo3YI3VqJ9y6Ga9GDoeUYCDQwHRwlars+OUdNZCeBa1s7joupiRs+G9Gmw9Fvg7TtRal3ZylL1at3r26K/I5TrUu/ArvsCHoqx46KKyKEPErp+uBAxJ7Zq3keBWnlh1NMKcBn07+m6fnszylFfFvyeu9JDUpRVhCsf12fkRzsAyB9EAVVBoIVuMiM9+vAW8Laf3LOrSzPJm4sheZMy6CvZ0u2u3M4KF2ZXoHh81puqThyGE9tBPN3rwLql9XjSA5Y46/r3dqPhH1gGhtK4by+C6GZRlNv4SjKkuctsjDMplxfdfqt2ypEmowJSvgKAoqAB21XFU+hoB/DLKd5AwdpzW8D8x0iUmNsSjqubG1yL/tNBVoHNgzXmMBlj04UMZWT3JiTVoles2AABN8NcytQ4lGasCu8c9QjhzpriHXSZsGo+/+IJdmkTL3Yjp8lmUYnX08LpeqypMDHYwtPEFSEm70SKZgmVDGHdcyiYbl8edPOmDmXDwXSbmENvWE8X9Jc74ya0tob/un4u+OJz6KhUnrAv8NDDITSV3il6LpaPeC0KbBjFjQvQb1Kf1L12Ef97D7VD0gMH5+JK2owygizYDdcZlQ420Rc36M4AxPHDVU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
