travis:
  secure:
    BINSTAR_TOKEN: JBnMBzT5UcrowlB5IXGzRoVmzSdoqXouoFuwD1jBEYTmmKYkXTC/NyciKgFNzwfa2zu1A8TKsSZ854qQT2GYlORXy6b8WKWHni1XYIsBGUMW+vIGLWkIexKghpbCDXK03aEyPHB1Fj9ZsBu78wbsmaubulO40a9BobgXKW1a8k7Rq7S6Q2U3+GUtDfyGVCF/8NyglpbnkdIu5SzuAJn4+0n6P92CT3cl667m6hncFMEo4PTeHIKF+ckTfyLtxrJfg0u6MXuD5JycK78eDFJFHpWk4OLvi1HpeGGyph4t8JTfsxGdAyYS3hoWXqBfCWohsiWX+BsqBWflB8i5xlEiQ9okWtlFWt7jG89ugCOVyGMimeT7CF8UIqWwI6OqaZjNFQ41NuMi99CXIiZsdcK5yplp0OUX9WvhWLv+hwQwvqXwUAZtwef8LEuUQnEWJ3ySRkyZL9j8KRMUY3UvnfdD4Th09JgtbEp2OgT0iqaBmcM7uNMgsCOR44Z/ZuLGL52pjhrAUZJaLUbUcZ0cXbP/L91AeE0Gzx0S6k0K01tfuA3ZAwwbXL9Cvsv31T0wLK1IvCD24bjKE3g1G3HrtAGXil5eOi6qNbt8PjxB4Br5e6GD+F/r/50Q4M4fuwN6XP7FsX+zniXnfMeuiyeo4qToyZvcnMwPBJM4PRSeagPN/y8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
