travis:
  secure:
    BINSTAR_TOKEN: uULYeN8vQJsaWmBL2ZtLNz2Lsmf/GWo2JFuDLFcoH4n6lDrfUtAapi2+2NNqJG4xIx189OiQ1fa249UOUflOieYqe6wCpj0J+Su3XaVPn7CtH4Dwm5PAWIJchod+RPw+bKFwpodZ65nvQdujQWihAE24S0FK0X/W/3TsY5WLbsoAiCUKVHiWShXgAPpuin2Hvio7nQDiVwiEK9j1/7zjk2LLtVa8yJm294+9GHfkKSGkij24+sNIlgp3dnqvMFx+/uYGdBBk9hHAWwlDeMSc2JBR3knyqCd1LTVao1uYC+pXTSDnV3JJbYYiIwBIa38ZtP6uXPC8zSjrcLRb3t2vGr7lWvZKYaDO2+9CPJfd0fZbxxh98ANKfsekEmXKWO6ciXBo4KWJ6Xz8cRT11c5S2nTuwMRAZV0+eNEMnz3HYxO2HqC142JABFostpwB4ym3iZemN4YWSuKHp0xogFhvndBvwbyN7Y+PXgcMDcfqd1fNDXwzs2cxB3Bg4Vf1vFXxJwgEr3PMgsTw7yyBoWx55hLrDPiGM+0HGpdKlibKKzCiYtx4Xw4r4Tr0waXNr/gGTnSs6LVLrATteMV5+a+oFyyJ3gTbuA6/JxrQHT5cuD+vwEXTZAGYM6InlrhpmGp+nFFnFCbUOZFUT/4dJci9F6d4HyeblBVs+3jB1rb0je4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
