travis:
  secure:
    BINSTAR_TOKEN: QnsjIaxCF+wxFev86ZT9gy65WQDk8tL0JUvRrOofF4dnlVO/dj0YgywD0gwoNJ+jvpkePxbROEd7QfWrt+3w+MSXKGw2Ii1NoT6ChStrCQ3BFV3/9aeqoFb/7YLadm7pwyhpm3XEoRfpDfmReo7803N5O8DoSQYsZMeUfD2fKJqgYDnGvqHBtvBv5emO+/XPClLVQM2JtmKaeoVqemFU/bEzmKG4PHr0rotSjMVpDmnyG5zT+MFw0QbVhIcR4L8zZBuLZaJV7U49A+hwEmze8YdYunNXatl0eeFiJ/KbHHRT0h4ucbn+TsoMB3S1GsVnixkhRxMHmEU1pEq8rVOpzPG1+1AdxPRkYbhjldYu1Jg/II0QBTRO/bW/lirhOjpUXAuRJnc7ZCG1pXNngX0YwfC8rY7sDgyzR0oR1oQ0Y+nY3HvIM1OBB/rPFtfbPU2MZFwA2GM8LcIzzO6kOQRDl0a8Z6smQjSb222FDiPUvr+9N13Acj9QIjPWGKiegls5cZWnsIzy3m96Lz2TUaicXuL2d2WVGP3liVWFicL/oOsj8owc9g6HxDAn/rUARi6nvFfdMBxf7f9oMBKn4DCmanGGBXDC43g9Ded8eFHAakwzyEt9XYoH9eDmCKRtoC5BqKMuDOn5S5ESwg218p1iMLzM2Ky9HJV/QgwGyztOzss=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
