travis:
  secure:
    BINSTAR_TOKEN: Ygehf6Suh3JO1W/Gqm6k/NI3vqSXhiDMgVJ8Tsgb7D0LIGgICgIfzHzPS5ABmX4djdCUNGM7mAI8CR5hhUsp88xucS5/gVmranajkVWFSdtT7c8MH6NTeFNZOtg7e/+zRf1ZcxRP98KeE4WUhsZQBfF3UUPFYKQ35XzOZUOrqqeE0Sh74Drst1NBdiDdFx9TCR7/3n611VsaMk9jUOZVRiQEjvMqsoLwc/A+3Oh7ZlLfMzm2/jUedibq+bbXMwE6oULB1MfHl445jRJMWjQJtteWH80pyGnc/xk/aotG7HkDPhlP69YHeeoKaCMhMIzwYOt7uOPN+0oJHEo+SDZdDwyAK5xgmKU0U25kOCpaYHlpL4UAVfvdUiINNyoEumo1GMoTtZcvudVKWN+w6EF58BvMAsI+Ay4ybz5406PBmm1hapBqwkGVDLWQjFOdEMaCyCjOXyE+JxPkyAibC4s0TCpvH9ENtwTSyZF4UvJmNFzY1ZIqZM4HrbbU9yNmQC8B4nBss5gv37ttpDpXY0Cf/ngBr8zIBUSJtCVF5wetWXQUhU85keYP7tI1VkndZGCt+L9s5cHj2sFNWJjC7+5ta2CiH/6+DIutBnGA2u7NLByG9ZzRgqmVkarvHkvOJYEr7A75D3FPSnUDG4eio3axcu4CYL5MTRLyprVZ4OSoi2c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
