travis:
  secure:
    BINSTAR_TOKEN: HAnEyxalM8V4KGIFwdChOfc98rdcEnaeZFkxExcKCh+fbG8Gmlt8KBQzkNuJW7gPIyQ+u+xIwdVrhiPTW4VU5hR7sSqhcHQ5pNazzerdfRQ1UBXgU5ZOLXHkWXybIYwgEtcMl+X4ovykD98fG5oVdtHcbfRq06cIn1oy8t3p24IZIhMpXECcU+SwlWx1Qs38qD/Kb6vBJUA+bbNk7gJ2ye+zxHzf4talMA5nf0zTkYWmRuk1sgvdjGH1ost3gojX3k7YROtZDW3oAXd13y+eTs68Hm1RDFnhopJnzOzLAzzc2JVuShUz6AaziikohA6NHAcOkJjeJRiaQ9z19kGtaCeYmsrCSaaQz3KV60fGTDWEJ18WZ4KgLgUqtNDKocvgOYTWiArIS2Ckn8ws2JjS9ZPdbTHFn8Gvaw8Ci8fJQE9G812cEHYNaopr+8trDL/Pt9MYzeJo+EoOnHOVPR4ry6JNrEZt9Tk4/cUVNOyhFGeannFD4SehuU4xAkVg9tJAyPC1AXaxUqRfsx30QqN9KX5PGHnxXMnI+IruMX9WgYLAQIFDQYe7mpZsyYgX6MjU3QtCdceTf2mwSakrJk64dXAi0z9YAZGlBlQ62UxVPkNf8nK048Eg+Q4xQ0+2dqfZDvUZIV6vhwQLY5Fsp6yhgERak37M6HEG5AkvEAfrrt8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
