travis:
  secure:
    BINSTAR_TOKEN: RYfjr6h/F3YWvikcgLR0bXA2xAlwD3QyL8nU3giGwqMG3Wffu0SxFmg61DUjj99cggfI9GRDvu2sVOZaX7OIwHRQxDbLPfgY2n7AzcOzPeeu/5VhIWl3KRTx3RLalHrw++O1sBVhzfqivBrePoiTurkJXo0B2s4wELTnEMFUBljvC+O3TTonxZH0ZhP/CXYeJ+CKFM0lxyCduHZFS9q/bUHEJDRp4LZ3ZoJeuEYz8179rNidLBWqcPi+8tzBhHVhZ/ejvwQNnW01a3bdK4KK0KPpgjsut/Pn5B81GpZ7DjDadu8Jwnz/R/0cpuWWRl8BpNT9bpzXTkQhmSX9wvWGjPD3oXJV256h5BlyhckhkkQjtMKJMug9wALHdOmCnPySXSLovoT6v1s/jgWubYi1rV4/VFCNDfQGE/tGoYbM2DzRL5UfdX0toTIxrXthVZ3E4HuM82p2pOKjNoeJTVadZP7nWCZaDKhpiSbvqu2i+5rZ/jZ4AhXCJ6yzPLAo8Vgoh8bWOTQT15xeILWw32w3sSMFmfAxmIndJ7yfLGq2SzqpgE5GBCmPDvk9eUvNl80lJiGJ3UWJv4Awo/ps7OV6M/M0DkI0k92QjrksmJO9rQk37XvSdGGkv7zM/l/z7s+qjNjRXZHJhAYjoig06UVIYPxhqKOat3Kv1BN9+1EWUUs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
