travis:
  secure:
    BINSTAR_TOKEN: d51LTEF/z/WEMCtbN5qbxGR/LeqyoavsVrlcsS4aqxyaSxj3pbqVl1+xW+k8y4OuiMXxlO+GNLfE60oRTUiGOz5+NWt6UeA87guMPaBV9vsSdMtysVsuv1qYARAE1fZWQm16KqSsf6wbHiWYERClkJnL+g6xKO9BXZ6S58ubT4VRwwhgN2qOnfHY7qd9r+kGrIcKnNK/U/A4OgEDVU/DAfvLCsHMum4qzBoNyW9bCj80spZNiJS6CVLcC66pgVWxzZr0gx3EMA8OXmqf36TPGpjbX5J6lBehHxtqdpuojFyDShIiYpVIsDxVpFq78fpOntCB06JubZefhiGQXKY8SqTySDlJOVUzZPk99HZS61TlqghmfTNzMBDd1xnXjegHNZqU0Bez/1sZAdzSzk+wTd+DMl7o4APzxJIGg0e0NrjGkqdEsLxYGjG23Vh1stXSU25KV00cUUUZQEXBjzX5mjY2JYkmp/Viv2yjPMTcWzMfZvftMssNvouDdJ2hV3Z8nI79sloxF/GwVYzw6gLaIYdvYym1JPv7uluORV8CLrYW12vWo95+eWBk/ulL2zv5PjK4MIP24KRW9tycmSdPcp0KCFs0+3PE7Hi4znDZ08/f4dIQxkoS6e4jFrdTJoidI0UCGyj2dtICOjw6QDvMPEUtjLfVH6SOl6IeX8Oz99M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
