travis:
  secure:
    BINSTAR_TOKEN: SuuWs+XbspS8Mhe/+xZEBoJpC80xwD7oXIh8NrJ2RcykumN+gZzvTX2BHoNU36nKbnmg8le5SNayplBYFLiWNxQ06/x9eXIC9an3m1BT1zaFZZnX6VxM+HFZTHKZfwPDXkwdOuW7SkZmGQrwO/55Ba1sY1TPly1heXTr0MTy8BoJNa86f/Syqr5UUFsEqRx/7JpZ5kghpBREAivXOmNo6GysF8BVsqFwknHyj1KFexd9oOYUltmfTY6rHGWSPxcOuTjfMoMs3F1cdJecGUi9kchzZ2t0WMgoQ83unaRbTc+fCvN+pAN8w0T/rh/1eV56N1jgpbOcKCq8LyMRJk6m62nlr+kbzQoFB/GpqIJFZuR9S4T05FnpJsNhOQA2YVUw75X93gOBBX4xpu1Ple3KmAYngfjXes+o4g+t8YUKou2SK6c+5oZGS3m78N4KCYJlykN9xJHVO/Uy3Ga/2xmxWoeNoakmV/1EaPfk7KTX+gap2pc+4uwynJMPPpuGbhKKe+kZjkRkQsTbPSZzG+A4JN3B7y2/vMEsLFUdEm/E8Srt7BLhaMDU9//8oJRymFWZ49FRrfWxILs6HdFzDx4k4llaP+Hd6UkwkXpYsBf9wQyP6OJKeDMgGe71nG1YuLBbrfAaoKQmqT/r45PNs7g3ognt9tT1FlgHoTZjOSZwLgo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
