travis:
  secure:
    BINSTAR_TOKEN: ZSJeWLe4Gz+C4161mRk63EEkU6DaPabzP8pOHLRStcmNVKttOqYc4bRXurNp/jxOYkAF/HAnTfIAEYFwd2O7KQqdjXFKQ39gN8fLXN0jvuq+BpnKMWJL7x/4Z07SvOPPSC+AQcQvZ2JoD5iofaNH802oqRWqpzMkg/oNAZ8wGPFqf2Rb1WQSHxY7FhogGIJRpcB0VoQRiR5RGA+aC41P81m2WrhkiJouZqJ+aVigW4I8fdx9jrY4wIz2RMZ+/6E4YP3CFIDqJhQsIEvclQ4TXxq7+XGkHf17i4Gc40IT28UoenXgM7ZGLFXcpBwnSSD0nqIb/kv/x9lAK5Ic0qQw63OlqtQ7T9IPg384kuGMFjDzxJ8jETHY3CD2TaNlrWOQ+C3Dy1CqwCaNpZh2ZQDKq6A/tdqfNoopq/h6+/mmBgHVpEco0lCJWcCisePyN+l5fNUQNoINYYqohhZN9HOSXRas76MjlNi6lT24WjnqxLMgH3K18WVEtT0dR/+GIIj7XWTdfVycTehBGZvbhmBvSp4T3o3QuAlRac/XKXq9whg1XyAveskgtjR4rXJV+c2FFsvrsFoD60nJa3tdWLqWjohujK+0iItQQuR0DBXnxmPw8885sgLOHOlztJLGOM2GuXseJBXg2Y0C1RlujyN/yoKcCPI/TUGw+xOvPKeIabA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
