travis:
  secure:
    BINSTAR_TOKEN: 0R1L5OAkf24TzxYkli3LfcLoPFZvw6zL0lrIMMOOTKlMO5ZgB3rSZPsdvB2nuClyZb1cI40SqQmlKdwCz5kDh0zUsD+HiIhro+e1Oynr/fBx94lb4W5u797nQ//ZGeOAE024ldA1wMWaEjKkVaYXjDTS6xf65TKOt25WghRKuyY33cUjHqY06F2CcTU+G306QHOzo+QmyTIPWCxM+16b3aADG2P4OKf/tsZNLsrSBDVBT1o+TIOYjSOKbTtHtnCiCIWYymHPFjjVETJFdnFdyoktlQ7bJSHQ35LEK/FowsOi/xNx2YAwbYRHwvZGz1yEG3AMrd45XMO4CZwrp7U8Ks/0oZhUZS3jE+qpT0Wfz3m3lLC4K+7IaN9v7bvfAYBUpY4aFk6WUuETqjc2oTd6dATCYAKGhvW5076bE1ldqnQAsyScao8OKNMqUsEiQgj52F03uMtIPoExkBqoOEjV8Z/2LJLlOBSQd/XHYwK+MNOal08t9Dq5PtnybuMOQ+H0VDoowdpr9rlV9S3bAjiKXEZCZldMxJFOHpof5VH49Zps2hJoCPMuONnhQ5K6cfGJ8oteWMRubqPgwSurHgIKRRNj8FMORNDKr4j/1zkoXnrzQJi3bVDRtUSFkCmRupeP7IZ7lzZilrkvCG/GW+jF9BLzGDOX5ZSw+qapmG2/63A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
