travis:
  secure:
    BINSTAR_TOKEN: QzVV6hgLVQoYPXveeV6HOPkrgWVbL0/H6DroDla8KNBs76Spf/XHResL1MS0t0L0fuXCigK/d7L9p4NaioVztKp8dDYZw45CxOKj0i3jhC7YndtMYvKlT7b03GFeNsO3jz4LOGuqPIBJItRieT4OqJIrhFT2/jjoGfGQu6fHuMmFwZmqcyDAkVs1GkC0kYg0fVmBmgeQhwTbcPZQ5b4V13Td16aNxHyk/whgjxV3ifTBMhVvcreNAc4dgpualFbAJ3d5fB9x809HqJt5GqPYTsS4ous3CRH3Qr4ktgd/f+0LYGkZpgMMJww8Azab6f6YNRA0Re/19oY/i5TwTe5DMH91eOr5pJKot6k3R8pNQVHToqFW2bsd/xgOZAa/jqA/R8v+bjnqOvjTBWi17ubbKXBsBC/fewmQg9/yXn+DxO4wXPn5A807dxnKOttqMDiCDZddzUA9pCsBA7ZhYygKq/2s3ShBOjc2gROnW21OLTRGXvn81HsXe0X9k7oMO43wn6mcAlvn5Z7SWA9v3zQpWObI++vtz0M7+v2fk/O+T7U+JHUCUzT2z7WhPe3fqi0g4C2a8eCFoyndmBH7jllAb009Ef2CvlgWOL2s6t9v0WvNX9+wic9kDzBC1BHdYHYfsCISUgsfdVJUZ/azf4h11WxxtUGBQI6N0wUsDaxCJnI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
