travis:
  secure:
    BINSTAR_TOKEN: dF2p4a1lMh5LsC43zpBHHoizsRs+6t5LWN3j0BH+mloeg7/gZ94RU/FIW5fKiTgJ+8Og5uU0f+INJ0eVvRqMjJv7Stpe1faQDdIRHHgxoftUM+jEJdmb/T91oVU3y2NdKeTI8pvN9nHKl1Rv009e0DIcmG6H+KhuwM9198Jj9azSFahNpXTXhyt1Lah4yg8dUwtikBq790q8Sc6OLkD4R2jl3mhIo7wjXIjS+sqxc/H/EyeLrbUNUoQYBUUkr7C0BLv8D7kPDMZ8MnyVPOOqIWF2Uuo+oOYhaluh1j+Bx2pYk+Hnb90ZR42WlT4cM8p5Sy/PeJ+aJb23zlgmJi3ZDxfqODMXsQPza6+wxt0vBrtSPSUX5W50IP7ewW2jvRf2xdjICYf42qYQNfc2slypAoRLKl80Co1MDBUO1wIz2AnQm8uYaqOuKUD5Bra1Gsy4i7c/511z0Dj342pwDyDk6VSNNVVEWadsc3GLOKiDvO1ni74JmdZdQT2adn+Euhs2vb+RPMjc074DP/0Ct8MlFWPkhLHDI3xCqRjlccfwKB4XXv6MDf9QKa3Fc/q0DgFva2NpwFlVrJwBFtldKe+rsvCTYuzwYtX+hVQzk6NLxWsG67PRxSSEKjEKq73te+oVpqUJGBq1db4uOoXSY0Gm6jTYCUoIiESnMyhgFHz7QMU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
