travis:
  secure:
    BINSTAR_TOKEN: wvplf9t99xv/081fQ1dJaU9a+NFydG3Aay+OmzZphbkHbW+py20wrNRzfgmJcfxE3uFR6xOpEH5vadUFgKr1/1TRL3CCdB4o25YHcGr/NX5b5+pq/cj2N7fIZgk0D5uLhqrMGkDRUpNEcA6N9J1GL2D7jsItjjN6LkEMAwxNsJIiSrZeKIXoKOTT6872TednHrkkSQXLQpy4jOjdXfMQqNox5vSpv3sEZ4lbO5lde/typusyZFgIt3ZGvk9AprC8Y6J73lZVtWPJYDg5v3tP+FQD8ImXH2LKhYzDb1uDQoEpEZW7Z1Bs509LKFEYDCd3g/39k9rNrLS1+WgFDi6TB7ubTPeKXo9cr6H761V3N0FSEKEq45uCkwSb9XrzoHCJnqeevXN7cgZH+MZhT0KZDZw0Xp5jxzT1qFqSs8ydJzUIKlzhWXArXeFjzd5tybMjhRFCKpN9HLsbjLJyfVMQU1tAq9gwp1m21WfjuFvqUchSo8osEouWM41R1FxvRFIWaEw2woNQ0Y1qQfmk9P3rPFqtR3ycf63B1qU/x3WOO/+NrO6cstYOb+qjsV5DJQ0vZPyyUlLRwlX14ixrKagreVoGm4X0NiZ5ezz7K5r6y3vYi0oF934MINOJaOCZ/JhEa5fzarNhTVlnqIiKHSI6cKUC5ZN693bOL17W++pjEJM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
