travis:
  secure:
    BINSTAR_TOKEN: 0XsqjoqUm2lIjmJKw88KSVVhrJq4Qsu5bMbMgjktpKrX5NjH94wQusWEGIodlkdPani9h4bH/9xpA/FRMusDpkDQiMI5pj3G564Od0SrAZEnH6zcoO96rfM1X4MQ8TxB7BVWwgBSgziuMW/fG+xFKu7tzudKeY1dpIXrNUSxnbTsH4zmDU8hvp7UQOU1+cUk7DJ/EPTiHshRMD+/bfHpdCWSPLHom3XHMZJGP9cn3I9umeMWdzpr5TAZxXdQYbjP1CjtFsf2iqwxp+I/pTmk53U32m7E/0+8Rx+hEIZ8FbiU49ddWmleE8ehQlYaQK8BcbRDbGQrWnmKqWkvuOtdp7d6ywQLpMQZcL/geG9onKGCUYi/pQ98cmYfNH9l1RjJ4EgU+v1+hDTJDdMPzrGyV9uxCMRzR4Z7ZqFQFwY6Hd5Nwu2prb+OUSH7UFR2/wT/GOzlSAr74KZcOk2nKkkH1npk24wRCotgeQe1bWCIGbk16SToBt/BsZIh+YGBwBHKiYQFympBf5hDciib4qT31YTuT7V7HRhqZMsqJYdRa3ZsNQjS1lN+SpuGsj1PXqsZJGnEb3cgYiM2YdSvwhg2WRsSkGvhn8UNAkMcXLfBLo06efkJETXGTLgLhRh0fu7IvhywmknIKYlibmjPROg6dbBVu2KDB6bcnO4mBkhN/uQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
