travis:
  secure:
    BINSTAR_TOKEN: KlKNX031A7keE2uI/4piGsGmOSt4A+ntyr+YlEBbIXSDLTTOqobuvuist6mWbdWHVzWgyeHT8BXGvjyboeQ0ndQ72LTZUSn72ByDy+5LEWin7xobO/ApyDQZUFYXQ3/MBxzXZEUnQmHEJ0ANhgLFI5oG6KwsGzE71MSN4pf6s4QcB+2wNeokjO+1tfaGe1AZxkybho6OozXk8/KykLws4xRTaqReG76bjq8iA149XNUcFyJLYUYbjIiZ24FVOjrjtuI6lyxrvh/l6tQ53bf62Q3UdiKHtaudzx5/r5nqyFL6X6HhATI7xCwR3PpltSHkrthpRxudEk129zN0u3LYqA8lMHA86loDOYmrMVjy9rJ2MTnEwFTW4bXdg3CKBz2yzIbs3wjlfqjq2AQCkrPyqSHdi+hZkn7jZfsPLSPVQmPjTE8t180H+BY4VaJhzgcNaGQ7LNEmJgP7KcpiCF+1wsQtq9FUC5XsSBeqnRl+5B54E+ycCC3+n2WhwM6oSnMG5OQGVzrqN022ta6KDKiH8jSNj31ujiCTdEJPO0CItz1f7f7p8Dar4nu0Lh/7KUyxgiY5uFY/b5DNKh7ayawdedpqfgWuWssdzoMCZKDLXy4/MncC9EIEtNscibh7dSl+boc3JH22puKl523jn5U1CQCb5Za0AQdxSbj6a0rscmM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
