travis:
  secure:
    BINSTAR_TOKEN: jWdNqUKWTxEzk7vmtE9fI9WoRrFRKhp12NmnhetkZgYGq1AB4Yh4ZXHaL+grli4iw3VJ0FHLzRhs97yZZE0x0+OfjEB8139ALtBPzN++NBCrGinils9DNlVQ85JJi3a4LFeGOO+xCZZFU4h6RIUCs9vt44XmIk3B3+bOT1DcYDdPrbdOUGkVCygKHlMWa3FwHSTrfUgSp+ZtrLlHN73W2/MqGA4RBCr6mwx7uZvkq0XOrgKVDjMcI8jb4KlflvlqHFePtHEtHHpZQBl8asfnlg9EJyCBk0PIPCKInyOdfnN51/MOTIZMM+1mStn2xqf4otCaq67gKBu1qN+mmvr08jeCZ0ANazJTgoJtYw19ryjtzTO9lMF5ZKBMEqJxLB0YePpiP/j+dPz8VkK7PO1Sp7ZuQVAuyc3ZfYIqyGeSiK2tOC8loo9wFxzwV8jHBkB+mbcriKtRPFQMccUeb8Z2iosCqyn1Xs6Cz9v7/N/nNGgRjVH+J/RxbqWEY4s2d2Ix42HLxD2/zkrW8tknv5pdthukfJlE5UL2mzbQSTYK0zutXMQfcvdjIul644Ro+IfoekZ65ZMI0DzErPv/mCNlDwJs7SKrNSSakCh2IeyH7eXv0lp14kKBxmzsr4+TM8TSr2OwnhhR9Kg96RjhbN0i4LZHm2bLANr/U5svXJFhfAY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
